FROM hoaln/hadoop-base-with-tez:3.2.2-java8
MAINTAINER HoaLN <l.ngochoa97@gmail.com>

HEALTHCHECK --interval=30s --timeout=10s --start-period=5m CMD curl -f http://localhost:8188/ || exit 1

ENV YARN_CONF_yarn_timeline___service_leveldb___timeline___store_path=/hadoop/yarn/timeline
RUN mkdir -p /hadoop/yarn/timeline
VOLUME /hadoop/yarn/timeline

ADD run.sh /run.sh
RUN chmod a+x /run.sh

EXPOSE 8188

CMD ["/run.sh"]
